### ISSUE TITLE
Alfred 3.0.2 [676]调试异常

### ISSUE THREAD

**Issue by droid-Q** [ethan-funny/Google-Alfred3-Workflow#1]
`[2016-07-08 20:55:04][ERROR: input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 41.)'. Row (null), Col (null): 'Specification mandate value for attribute error' in XML:
<urlopen error [Errno 8] nodename nor servname provided, or not known>`

**Comment by ethan-funny** [comment]
谢谢反馈。因为我用的是 Alfred 3，有些特性估计在 Alfred 2 中不能用，建议升级到 Alfred 3。

**Comment by droid-Q** [comment]
@ethan-funny  是我打错了，我的版本是v3.0.2 [676]

**Comment by droid-Q** [comment]
已发现问题所在，alfred3 advanced 中取消use OS X http proxy
