### ISSUE TITLE
按shift也会弹出预览页面，导致输入法不能切换中英文

### ISSUE THREAD

**Issue by iblogc** [ethan-funny/Google-Alfred3-Workflow#11]

**Comment by ethan-funny** [comment]
你好，`shift` 键确实可以预览，但由于输入法也使用 `shift` 键切换中英文，推荐使用 `command + y` 键，你也可以把 `shift` 键的预览功能关闭，如图：

![image](https://cloud.githubusercontent.com/assets/2676138/24843204/1a2e3a80-1dd3-11e7-98d2-59ca148027ba.png)

**Comment by iblogc** [comment]
没看到还有这个设置，谢谢。

Ethan <notifications@github.com>于2017年4月10日周一 上午9:52写道：
