### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by laxapple** [ethan-funny/Google-Alfred3-Workflow#2]
My proxy is working fine, but there is no result showing up. Here's debugging log in Alfred 3:

> Starting debug for 'Google Search'
> 
> [2016-07-12 12:56:14][input.scriptfilter] ''
> <items />
> [2016-07-12 12:56:14][ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
> ''
> <items />
> [2016-07-12 12:56:24][input.scriptfilter] ''
> <items />

**Comment by ethan-funny** [comment]
Did you config socks proxy?

**Comment by laxapple** [comment]
是的，ShadowsocksX 和 GoagentX 配置了，都无效。尝试用 Proxifier 让 Alfred 走代理也不行。
然后翻到你 Blog 文章《在 Python 中使用 socks 代理》，测试脚本发现墙内网址 http/https 均正常，墙外均报错：

http

> requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

https

> requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:590)

**Comment by ethan-funny** [comment]
你看看能不能 fix 一下，给我提交一个 pull request，不知道是配置的问题还是其他问题引起的，我也再看一下，谢谢反馈~

**Comment by laxapple** [comment]
研究半天，Requests 新版已经支持 PySocks 的 socks5 代理，改用 Requests替换 urllib2 方法，修改一处小编码问题，终于可以出来搜索结果了。https://github.com/laxapple/Google-Alfred3-Workflow/releases

目前还有几点问题
1. 搜索结果和 Chrome/Safari 隐身模式 Google Account 非登录状态下的搜索顺序和内容不一致
![Screen Shot 2016-07-14 at 23.48.58.png](http://ww2.sinaimg.cn/large/72f96cbagw1f5tvg14021j21gr0rln9j.jpg)
1. 加了 lr=lang_en 参数后还是经常出现残余日文结果项（代理为日本 IP）
   ![Screen Shot 2016-07-14 at 23.55.37.png](http://ww1.sinaimg.cn/large/72f96cbagw1f5tvmblvlzj20fi0cz787.jpg)
2. 极少情况下中文 title 无法显示，比如“gs 淘宝”结果第二条 title “天猫”不显示
   ![Screen Shot 2016-07-14 at 23.58.22.png](http://ww1.sinaimg.cn/large/72f96cbajw1f5tvnipcg8j20fh0czgph.jpg)
3. ⇧ 触发的是“{query};url”字符串而不是网页的 Quicklook
   ![Screen Shot 2016-07-15 at 00.03.38.png](http://ww3.sinaimg.cn/large/72f96cbagw1f5tvtjzmndj20hr0dbwgf.jpg)

**Comment by ethan-funny** [comment]
谢谢 @laxapple 。
- 关于搜索顺序不一致。这个问题我也遇到过，经研究发现，在代码里改 `user_agent`，搜索结果也会发生一些变化，大概想到 google 的搜索结果不是一成不变的，搜索排序会受到多种因素的影响，不过还可以接受。
- 关于出现其他语言的结果项。估计这个跟代理什么的有些关系，这个暂时没想到什么好的解决方法。
- 在某些情况下，中文 title 无法显示，这个是因为在解析 html 页面的时候，极少部分 html 标记跟其他的不一样，导致解析的时候获取不到标题。
- ⇧ 触发的是“{query};url”字符串。这个当时介绍的时候有点失误，没有预览网页这个功能的，因为为了能输出 markdown 形式的链接，所以按 `shift` 键出来的是『{query};url』的字符串，而不是『url』的字符串。

**Comment by laxapple** [comment]
解决了几个问题
- 搜索结果顺序问题
  Alfred 有个智能排序的特性（基于 item UID 实现），这对快捷启动来说是必要的。这个特性对本 workflow 同样有效，特定关键字查询“智能排序”是可以接受的，但要命的是它是 workflow全局的，即对搜索结果的操作将会影响以后每次搜索结果顺序，久而久之，最后排序一片混乱。去掉 item 对象的 uid 即可解决。
- 请求 url 换成 https://encrypted.google.com ，然后世界清净了
- 你的源码里 markdown 输出的 {query};url，改成 title;url 更合理。
  我还是认为预览功能更重要，个人水平有限，只能输出纯 url 实现预览而无法兼顾 markdown。

由于 Alfred 3 扩展了 Variables 功能，你可否研究一下，脚本里将 title 赋值给 variable，再通过 “Args and Vars” 控件输出 markdown。
参考 [Workflow/environment variables](http://www.alfredforum.com/topic/9070-how-to-workflowenvironment-variables/)

**Comment by ethan-funny** [comment]
赞 👍 ，我找时间研究一下，不过最近工作比较忙，估计没那么快，弄好了通知你 @laxapple 。

**Comment by ethan-funny** [comment]
@laxapple ，关于  Variables 功能，你可以看看这个例子，https://www.alfredapp.com/help/workflows/advanced/variables/

**Comment by laxapple** [comment]
研究过，官方文档都是针对一般用户 GUI 用法，我上面那个参考链接给出了代码级传递 Variables 的方法。
“gs {query}” 的搜索结果 Item 有 title，subtitle， arg 等属性，其中 arg 作为下个 Obj 的 input，把 arg 值设为 url 即可直接实现预览、打开、复制功能。
问题来了，在不影响上述功能前提下，如何获取 title 以设置 markdown？

**Comment by ethan-funny** [comment]
其实当时写的时候，也有考虑到这个问题，但当时发现获取 markdown url 和预览两个功能有点冲突，只好选择自己比较常用的一个功能。下午看了一下你发的那个链接，试了一下，好像还是不行。。

**Comment by laxapple** [comment]
昨天研究出了获取 $title 的 hack 办法，可惜输出的 url 是 json 对象，仍不能预览，疑似 Alfred bug。
无奈之下求助论坛，经大牛点拨，将数据保存到 json 文件完美解决。当时看到 port 写在文件里我怎么就没想到这点呢？还是 Too Y, too S, sometimes N.
