### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by sundarv85** [ethan-funny/Google-Alfred3-Workflow#6]
When I type "gs" I see the Google Search Workflow listed

But when I type in some keywords, then I see my default search options. Am I missing something?

**Comment by ethan-funny** [comment]
Are you using alfred3, it works only for alfred3.

**Comment by sundarv85** [comment]
Yes, I'm using Alfred3. I'm using macOS Sierra.. if that makes a difference

**Comment by ethan-funny** [comment]
I'm sorry that the bug can't be reproduced in my situation. So you can send me a pull request if you can fix this bug. Thank you!

**Comment by sundarv85** [comment]
I found the issue. In your search.py, you have the code

`from google import google`

I already have google module present in my global python libraries and hence it is trying to import google from my global google module, and not from your local google folder.

If you could rename your google folder to "alfred-google", then it shall start to work.
